"""add analysis_cache table

Revision ID: 88d56ab21fcc
Revises: 670fe05b0579
Create Date: 2025-12-14 12:05:27.575857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d56ab21fcc'
down_revision: Union[str, None] = '670fe05b0579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'analysis_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('repo_url', sa.String(), nullable=False),
        sa.Column('data', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_cache_repo_url'), 'analysis_cache', ['repo_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_cache_repo_url'), table_name='analysis_cache')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
