"""Update timestamps to use server_default func.now()

Revision ID: da3de5c8cc0a
Revises: a1b2c3d4e5f6
Create Date: 2025-12-21 14:07:01.414999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3de5c8cc0a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        # Nullable to avoid failing on existing databases with pre-user deployments.
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_deployments_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_deployments_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            existing_nullable=False,
        )

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            existing_nullable=False,
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=sa.text('CURRENT_TIMESTAMP'),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(timezone=True),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.alter_column(
            'updated_at',
            existing_type=sa.DateTime(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DateTime(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_constraint('fk_deployments_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_deployments_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
